version: "3.3"

services:
  app:
    command: >
      sh -c "cd src && poetry run python manage.py runserver 0.0.0.0:8000"
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - .env
